version: '3.4'

networks:
  velozient-drone-delivery-service-v3-net:
    driver: bridge

services:
  velozient-drone-delivery-service-v3-debug:
    # env_file:
    #   - ../.env
    build:
      context: ./
      dockerfile: alpine.debug.Dockerfile
      target: debug
    volumes:
      - ..:/usr/src/app
    networks:
      - velozient-drone-delivery-service-v3-net
    # ports:
    #   - "3002:3002"
    container_name: velozient-drone-delivery-service-v3-debug
    image: velozient-drone-delivery-service-v3-debug:latest
    command: /bin/sh -c "while sleep 1000; do :; done"
    tty: true
